In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas
from collections import Counter
from matplotlib.patches import Rectangle
import seaborn as sns
import urllib2

In [2]:
nbtable = np.zeros((6,6))

In [3]:
for chrnum in range(1,23):
    OnTAD_raw = pandas.read_table(urllib2.urlopen('http://bx.psu.edu/~lua137/OnTAD/output/OnTAD/Gm12878/10kb/OnTAD_KRnorm_pen0.1_max200_hsz5_chr'+str(chrnum)+'.tad'),sep='\t',header=None)
    OnTAD_rawa = OnTAD_raw.loc[(OnTAD_raw[2]>0),:].values[:,0:2]-1
    OnTAD_rawb = np.unique(OnTAD_rawa.flatten())
    for i in OnTAD_rawb:
        nbtable[min(5,np.count_nonzero( OnTAD_rawa[:,0] == i)), min(5,np.count_nonzero( OnTAD_rawa[:,1] == i))] +=1

In [4]:
print nbtable.astype(int)

[[   0 1297  378  110   23    9]
 [1209 2108 1060  375   77   19]
 [ 428 1023  524  214   80   27]
 [ 100  413  247  136   41    7]
 [  22   71   61   35   12    3]
 [   7   24   17   17    5    1]]


In [5]:
from scipy.stats import chi2_contingency

In [6]:
chi2_contingency(nbtable)

(946.28006352159866,
 1.427958816205889e-183,
 25,
 array([[  3.15208448e+02,   8.81012967e+02,   4.08200295e+02,
           1.58318173e+02,   4.24799607e+01,   1.17801572e+01],
        [  8.41018468e+02,   2.35066090e+03,   1.08913320e+03,
           4.22414145e+02,   1.13342240e+02,   3.14310413e+01],
        [  3.98304126e+02,   1.11326680e+03,   5.15810609e+02,
           2.00054224e+02,   5.36785855e+01,   1.48856582e+01],
        [  1.63762672e+02,   4.57719450e+02,   2.12075442e+02,
           8.22522593e+01,   2.20699411e+01,   6.12023576e+00],
        [  3.53893910e+01,   9.89139489e+01,   4.58298625e+01,
           1.77748527e+01,   4.76935167e+00,   1.32259332e+00],
        [  1.23168959e+01,   3.44259332e+01,   1.59505894e+01,
           6.18634578e+00,   1.65992141e+00,   4.60314342e-01]]))

In [14]:
from statsmodels.stats.proportion import proportions_ztest

In [15]:
count = np.sum(nbtable.diagonal())
nobs = np.sum(nbtable)
value = .5
stat, pval = proportions_ztest(count, nobs, value, alternative='smaller')

In [17]:
print pval

0.0
